# support 256 colors or true colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"
set -ga terminal-features ",*:truecolor:focus"

# allow reload tmux config
unbind r
bind R source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# enable mouse mode
set -g mouse on

# start indexing from 1
set -g base-index 1
setw -g pane-base-index 1

# vi keys
setw -g mode-keys vi

# vim style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize panes (Alt + h/j/k/l)
bind -T root M-h resize-pane -L 2
bind -T root M-j resize-pane -D 2
bind -T root M-k resize-pane -U 2
bind -T root M-l resize-pane -R 2

# change prefix key
set-option -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

# don't detach on destroy
set -g detach-on-destroy off

# open new windows/splits in the current pane's working directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# sesh session switcher
bind K display-popup -E -w 80% -h 90% -d '#{pane_current_path}' -T 'Sesh' tv sesh
bind -N "Sesh: last session" L run-shell "sesh last"

# --- Plugin Manager ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# Restore on tmux start (continuum)
set -g @continuum-restore 'on'

# Yank to system clipboard
set -g @yank-selection 'primary'

# Initialize TMUX plugin manager (keep at bottom)
run '~/.config/tmux/plugins/tpm/tpm'
