require("plugins.options")
require("plugins.keymaps_autoload")

require("plugins.catppuccin")
require("plugins.indent")
require("plugins.which_key")
require("plugins.snacks")
require("plugins.plenary")
require("plugins.todo_comment")
require("plugins.gitsign")
require("plugins.noice")
require("plugins.trouble")
require("plugins.treesitter")
require("plugins.mini")
-- require("plugins.lualine")
require("plugins.yazi")
require("plugins.tmux_navigator")
require("plugins.fishbone")
